
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "norbjert"
    target-branch: "master"
    auto-merge:
      enabled: true
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
    # Only merge if all tests pass
    merge:
      strategy: "auto"
      # This ensures PRs are only merged if all required checks pass
      require-all-status-checks: true